[program:mqtt-subscriber]
process_name=%(program_name)s_%(process_num)02d
command=php artisan mqtt:subscribe
directory=C:\Users\USER\Desktop\RainWater Cath Basin\IOT\RainwaterCatchBasin
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=storage/logs/mqtt-subscriber.log
stopwaitsecs=3600 