[program:mqtt-subscriber]
process_name=%(program_name)s_%(process_num)02d
command=php artisan mqtt:subscribe
directory=/home/orangepi/RainwaterCatchBasin
autostart=true
autorestart=true
user=orangepi
numprocs=1
redirect_stderr=true
stdout_logfile=/home/orangepi/RainwaterCatchBasin/storage/logs/mqtt-subscriber.log
stopwaitsecs=3600

[program:watersensor]
process_name=%(program_name)s_%(process_num)02d
command=python3 watersensor_read.py
directory=/home/orangepi/RainwaterCatchBasin
autostart=true
autorestart=true
user=orangepi
numprocs=1
redirect_stderr=true
stdout_logfile=/home/orangepi/RainwaterCatchBasin/storage/logs/watersensor.log
stopwaitsecs=3600 