[supervisord]
logfile=supervisor/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
pidfile=supervisor/supervisord.pid
nodaemon=false

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=http://127.0.0.1:9001

[inet_http_server]
port=127.0.0.1:9001

[program:mqtt-subscriber]
process_name=%(program_name)s_%(process_num)02d
command=php artisan mqtt:subscribe
directory=C:\Users\USER\Desktop\RainWater Cath Basin\IOT\RainwaterCatchBasin
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=storage/logs/mqtt-subscriber.log
stopwaitsecs=3600 